# Generated by Django 6.0.1 on 2026-02-02 20:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_en', models.CharField(max_length=50, null=True, unique=True)),
                ('name_de', models.CharField(max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_en', models.CharField(max_length=50, null=True, unique=True)),
                ('name_de', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('youtube_id', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('likes_current', models.PositiveIntegerField(default=0)),
                ('views_current', models.PositiveIntegerField(default=0)),
                ('comments_current', models.PositiveIntegerField(default=0)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_recorded', models.DateField(blank=True, db_index=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='videos.category')),
                ('tags', models.ManyToManyField(blank=True, to='videos.tag')),
            ],
        ),
        migrations.CreateModel(
            name='VideoStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='videos.video')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
    ]
