# Generated by Django 6.0.1 on 2026-02-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date_recorded',
            field=models.DateField(db_index=True, default="2026-02-03"),
            preserve_default=False,
        ),
    ]
