# Generated by Django 6.0.1 on 2026-02-09 19:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_date_recorded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('size_inch', models.PositiveSmallIntegerField()),
                ('weight_grams', models.PositiveIntegerField()),
                ('frame', models.CharField(blank=True, max_length=100)),
                ('motors', models.CharField(blank=True, max_length=100)),
                ('esc', models.CharField(blank=True, max_length=100)),
                ('flight_controller', models.CharField(blank=True, max_length=100)),
                ('camera', models.CharField(blank=True, max_length=100)),
                ('vtx', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='video',
            name='altitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='time_of_day',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night'), ('sunrise', 'Sunrise'), ('golden_hour', 'Golden Hour'), ('sunset', 'Sunset')], max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='weather',
            field=models.CharField(blank=True, choices=[('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('snowy', 'Snowy'), ('foggy', 'Foggy')], max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='drone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.drone'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['category', 'country', 'date_recorded'], name='videos_vide_categor_4cc03f_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['country', 'state'], name='videos_vide_country_748b62_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['date_recorded'], name='videos_vide_date_re_5dd13c_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-views_current'], name='videos_vide_views_c_6569c3_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-likes_current'], name='videos_vide_likes_c_777a38_idx'),
        ),
    ]
