# Generated by Django 6.0.1 on 2026-02-09 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_drone_category_name_fr_tag_name_fr_video_altitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='drone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.drone'),
        ),
    ]
