# Generated by Django 6.0.1 on 2026-02-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drones/'),
        ),
    ]
