# Generated by Django 6.0.1 on 2026-02-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_drone_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='image',
            field=models.ImageField(upload_to='drones/'),
        ),
    ]
