# Generated by Django 6.0.1 on 2026-02-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_drone_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='size_inch',
            field=models.FloatField(),
        ),
    ]
