# Generated by Django 6.0.1 on 2026-02-14 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='longitude',
        ),
    ]
