# Generated by Django 6.0.1 on 2026-02-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_remove_picture_altitude_remove_picture_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='region',
            new_name='place',
        ),
    ]
