# Generated by Django 6.0.1 on 2026-02-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_rename_region_video_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='season',
            field=models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter')], max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='time_of_day',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Night', 'Night'), ('Sunrise', 'Sunrise'), ('Golden Hour', 'Golden Hour'), ('Sunset', 'Sunset')], max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='weather',
            field=models.CharField(blank=True, choices=[('Sunny', 'Sunny'), ('Cloudy', 'Cloudy'), ('Rainy', 'Rainy'), ('Snowy', 'Snowy'), ('Foggy', 'Foggy')], max_length=20),
        ),
    ]
